# Base configs
baseurl: ''

# UI configs
title: "Jinay Panchal"
name: "Jinay Panchal"
bio: "A Pythonista"
social_urls:
  facebook: "https://www.facebook.com/jinaypanchal"
  twitter: ""
  instagram: ""
